name : First CI workflow

on:
  push:
    branches: 
      - [ "master" ]
  pull_request:
    branches: 
      - [ "master" ]

jobs:
  runs-on : ubuntu-latest
  stpes:
    - name : chekout
      uses : actions/checkout@v4

    - name : python setup
      uses : actions/setup-python@v4
      with:
        python-version : '3.13.3'
    
    - name : install dependencies
      run : | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name : run test 
      run : | 
        pytest
    
