name : First CI workflow

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:


  job1:
    runs-on : ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v4

      - name : python setup
        uses : actions/setup-python@v4
        with:
          python-version : '3.13.3'
      
      - name : install dependencies
        run : | 
          python -m pip install --upgrade pip
          pip install -r artefacts/requirements.txt

      - name : run test 
        run : | 
          pytest

  job2:
    needs : job1
    runs-on : ubuntu-latest
    steps:
      - name : Login to Docker
        uses : actions/checkout@v4
      - name : Login to Docker
        uses : docker/login-action@v3
        with:
          username : ${{ secrets.DOCKER_USERNAME }}
          password : ${{ secrets.DOCKER_PASS }}

      - name : Build and push Docker image
        uses : docker/build-push-action@v6
        with:
          push: true
          tags: kavinesht/create-repo:latest
